const fs = require('fs');
const p = 'd:\\KKU_Final\\nutrition-app\\my-app\\app\\register\\step7.tsx';
const L = [];
L.push('import React, { useState, useEffect } from "react";');
L.push('import { View, Text, TouchableOpacity, ScrollView, TextInput, ActivityIndicator, KeyboardAvoidingView, Platform } from "react-native";');
L.push('import { SafeAreaView } from "react-native-safe-area-context";');
L.push('import { router } from "expo-router";');
L.push('import { Ionicons } from "@expo/vector-icons";');
L.push('import { useRegister } from "../../context/register-context";');
L.push('import styles, { ORANGE, ROW_COLOR_1, ROW_COLOR_2 } from "./step7.styles";');
L.push('import { API_BASE_URL } from "../../constants/config";');
L.push('');
L.push('type FoodItem = { id: string; name: string };');
L.push('type SubCategory = { id: string; name: string; items: FoodItem[] };');
L.push('type L1Category = { id: string; name: string; subCategories: SubCategory[] };');
L.push('');
L.push('export default function RegisterStep7Screen() {');
L.push('  const { form, updateForm } = useRegister();');
L.push('  const [isLoading, setIsLoading] = useState(true);');
L.push('  const [categories, setCategories] = useState<L1Category[]>([]);');
L.push('  const [selectedFoods, setSelectedFoods] = useState<Set<string>>(new Set());');
L.push('  const [searchQuery, setSearchQuery] = useState("");');
L.push('  const [expandedL1, setExpandedL1] = useState<Set<string>>(new Set());');
L.push('  const [expandedL2, setExpandedL2] = useState<Set<string>>(new Set());');
L.push('');
L.push('  useEffect(() => {');
L.push('    const fetchDislikedFoods = async () => {');
L.push('      try {');
L.push('        const response = await fetch(`${API_BASE_URL}/disliked-foods`);');
L.push('        const result = await response.json();');
L.push('        if (result?.data) {');
L.push('          setCategories(result.data);');
L.push('          const safe: any = form.dislikedFoods || {};');
L.push('          const restored = new Set<string>();');
L.push('          if (!Array.isArray(safe)) {');
L.push('            Object.keys(safe).forEach((k) => { (safe[k] || []).forEach((item: string) => restored.add(item)); });');
L.push('          }');
L.push('          setSelectedFoods(restored);');
L.push('        }');
L.push('      } catch (e) { console.error("Fetch Error:", e); } finally { setIsLoading(false); }');
L.push('    };');
L.push('  const toggleFood = (name: string) => { const n = new Set(selectedFoods); n.has(name) ? n.delete(name) : n.add(name); setSelectedFoods(n); };');
L.push('  const removeSelected = (name: string) => { const n = new Set(selectedFoods); n.delete(name); setSelectedFoods(n); };');
L.push('  const toggleL1 = (id: string) => { setExpandedL1((p) => { const n = new Set(p); n.has(id) ? n.delete(id) : n.add(id); return n; }); };');
L.push('  const toggleL2 = (key: string) => { setExpandedL2((p) => { const n = new Set(p); n.has(key) ? n.delete(key) : n.add(key); return n; }); };');
L.push('  const toggleL1All = (cat: L1Category) => { const ns: string[] = []; cat.subCategories.forEach((s) => s.items.forEach((i) => ns.push(i.name))); const a = ns.length > 0 && ns.every((n) => selectedFoods.has(n)); const x = new Set(selectedFoods); a ? ns.forEach((n) => x.delete(n)) : ns.forEach((n) => x.add(n)); setSelectedFoods(x); };');
L.push('  const toggleL2All = (sub: SubCategory) => { const ns = sub.items.map((i) => i.name); const a = ns.length > 0 && ns.every((n) => selectedFoods.has(n)); const x = new Set(selectedFoods); a ? ns.forEach((n) => x.delete(n)) : ns.forEach((n) => x.add(n)); setSelectedFoods(x); };');
L.push('  const l1Count = (cat: L1Category) => { let c = 0; cat.subCategories.forEach((s) => s.items.forEach((i) => { if (selectedFoods.has(i.name)) c++; })); return c; };');
L.push('  const l2Count = (sub: SubCategory) => sub.items.filter((i) => selectedFoods.has(i.name)).length;');
L.push('  const l1State = (cat: L1Category): "all" | "partial" | "none" => { let t = 0, s = 0; cat.subCategories.forEach((sub) => sub.items.forEach((i) => { t++; if (selectedFoods.has(i.name)) s++; })); if (!t || !s) return "none"; return s === t ? "all" : "partial"; };');
L.push('  const l2State = (sub: SubCategory): "all" | "partial" | "none" => { const t = sub.items.length, s = sub.items.filter((i) => selectedFoods.has(i.name)).length; if (!t || !s) return "none"; return s === t ? "all" : "partial"; };');
L.push('  const checkIcon = (st: string) => st === "all" ? "checkbox" : st === "partial" ? "checkbox-outline" : "square-outline";');
L.push('  const filtered = searchQuery.trim() ? categories.map((c) => ({ ...c, subCategories: c.subCategories.map((s) => ({ ...s, items: s.items.filter((i) => i.name.toLowerCase().includes(searchQuery.toLowerCase())) })).filter((s) => s.items.length > 0) })).filter((c) => c.subCategories.length > 0) : categories;');
L.push('  const selectedArray = Array.from(selectedFoods);');
L.push('  const handleNext = () => { const data: Record<string, string[]> = {}; categories.forEach((cat) => cat.subCategories.forEach((sub) => sub.items.forEach((item) => { if (selectedFoods.has(item.name)) { if (!data[cat.id]) data[cat.id] = []; data[cat.id].push(item.name); } }))); updateForm({ dislikedFoods: data as any }); router.push("/register/step8" as any); };');
L.push('');
L.push('  if (isLoading) { return (<SafeAreaView style={[styles.container, { justifyContent: "center", alignItems: "center" }]}><ActivityIndicator size="large" color={ORANGE} /><Text style={{ marginTop: 16, color: "#666", fontFamily: "NotoSansThaiBold" }}>กำลังโหลดข้อมูล...</Text></SafeAreaView>); }');
L.push('');
L.push('    fetchDislikedFoods();');
L.push('  return (');
L.push('    <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === "ios" ? "padding" : undefined}>');
L.push('      <SafeAreaView style={styles.container}>');
L.push('        <View style={styles.headerBar}><Text style={styles.headerText}>ลงทะเบียนผู้ใช้งาน</Text></View>');
L.push('        <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">');
L.push('          <Text style={styles.stepTitle}>7. อาหารที่ไม่ชอบ</Text>');
L.push('          <View style={styles.progressTrack}><View style={[styles.progressFill, { width: "87.5%" }]} /></View>');
L.push('          <Text style={styles.subtitle}>เลือกประเภทอาหารที่คุณไม่ชอบรับประทาน</Text>');
L.push('          <View style={styles.searchContainer}>');
L.push('            <Ionicons name="search-outline" size={18} color="#999" />');
L.push('            <TextInput style={styles.searchInput} placeholder="ค้นหาอาหาร..." placeholderTextColor="#AAA" value={searchQuery} onChangeText={setSearchQuery} autoCapitalize="none" autoCorrect={false} />');
L.push('            {searchQuery.length > 0 && (<TouchableOpacity onPress={() => setSearchQuery("")}><Ionicons name="close-circle" size={18} color="#999" /></TouchableOpacity>)}');
L.push('          </View>');
L.push('          <View style={styles.categoriesWrap}>');
L.push('            {filtered.map((cat, ci) => {');
L.push('              const isOpen = expandedL1.has(cat.id);');
L.push('              const st = l1State(cat); const cnt = l1Count(cat);');
L.push('              const bg = ci % 2 === 0 ? ROW_COLOR_1 : ROW_COLOR_2;');
L.push('              return (');
L.push('                <View key={cat.id}>');
L.push('                  <View style={[styles.categoryRow, { backgroundColor: bg }]}>');
L.push('                    <TouchableOpacity onPress={() => toggleL1All(cat)} style={{ marginRight: 10 }} activeOpacity={0.7}>');
L.push('                      <Ionicons name={checkIcon(st) as any} size={22} color="#FFF" />');
L.push('                    </TouchableOpacity>');
L.push('                    <TouchableOpacity style={{ flex: 1, flexDirection: "row", alignItems: "center" }} onPress={() => toggleL1(cat.id)} activeOpacity={0.7}>');
L.push('                      <Text style={styles.categoryText}>{cat.name}</Text>');
L.push('                      {cnt > 0 && <View style={styles.badge}><Text style={styles.badgeText}>{cnt}</Text></View>}');
L.push('                    </TouchableOpacity>');
L.push('                    <TouchableOpacity onPress={() => toggleL1(cat.id)} activeOpacity={0.7}>');
L.push('                      <Ionicons name={isOpen ? "chevron-up" : "chevron-down"} size={20} color="#FFF" />');
L.push('                  {isOpen && (<View style={styles.subListWrapOuter}>');
L.push('                    {cat.subCategories.map((sub, si) => {');
L.push('                      const l2Key = `${cat.id}__${sub.id}`;');
L.push('                      const isL2 = expandedL2.has(l2Key);');
L.push('                      const s2 = l2State(sub); const c2 = l2Count(sub);');
L.push('                      return (');
L.push('                        <View key={sub.id}>');
L.push('                          <TouchableOpacity style={[styles.subItemRow, si < cat.subCategories.length - 1 && styles.subItemRowBorder, { paddingLeft: 20 }]} onPress={() => toggleL2(l2Key)} activeOpacity={0.7}>');
L.push('                            <View style={{ flexDirection: "row", alignItems: "center", flex: 1 }}>');
L.push('                              <TouchableOpacity onPress={() => toggleL2All(sub)} style={{ marginRight: 8 }} activeOpacity={0.7}>');
L.push('                                <Ionicons name={checkIcon(s2) as any} size={20} color={s2 === "none" ? "#CCC" : ORANGE} />');
L.push('                              </TouchableOpacity>');
L.push('                              <Text style={[styles.subItemText, { fontFamily: "NotoSansThaiBold", fontSize: 15 }]}>{sub.name}</Text>');
L.push('                              {c2 > 0 && <View style={[styles.badge, { marginLeft: 8 }]}><Text style={styles.badgeText}>{c2}</Text></View>}');
L.push('                            </View>');
L.push('                            <Ionicons name={isL2 ? "chevron-up" : "chevron-down"} size={18} color="#999" />');
L.push('                          </TouchableOpacity>');
L.push('                          {isL2 && sub.items.map((food, fi) => {');
L.push('                            const sel = selectedFoods.has(food.name);');
L.push('                            return (');
L.push('                              <TouchableOpacity key={food.id} style={[styles.subItemRow, fi < sub.items.length - 1 && styles.subItemRowBorder, { paddingLeft: 52 }]} onPress={() => toggleFood(food.name)} activeOpacity={0.7}>');
L.push('                                <Text style={styles.subItemText}>{food.name}</Text>');
L.push('                                <View style={[styles.badge, { backgroundColor: sel ? ORANGE : "#F0F0F0", borderColor: sel ? ORANGE : "#E5E5E5", borderWidth: 1 }]}>');
L.push('                                  <Ionicons name={sel ? "checkmark" : "add"} size={16} color={sel ? "#FFF" : "#999"} />');
L.push('                                </View>');
L.push('                              </TouchableOpacity>');
L.push('                            );');
L.push('                          })}');
L.push('                        </View>');
L.push('                      );');
L.push('                    })}');
L.push('                  </View>)}');
L.push('                </View>');
L.push('              );');
L.push('            })}');
L.push('          </View>');
L.push('                    </TouchableOpacity>');
L.push('          <View style={styles.summaryBox}>');
L.push('            <Text style={styles.summaryTitle}>สรุปรายการที่ไม่ชอบ</Text>');
L.push('            {selectedArray.length > 0 ? (<View style={styles.summaryChipWrap}>{selectedArray.map((item) => (<View key={item} style={styles.summaryChip}><Text style={styles.summaryChipText}>{item}</Text><TouchableOpacity onPress={() => removeSelected(item)} activeOpacity={0.8}><Text style={styles.summaryChipRemove}>✕</Text></TouchableOpacity></View>))}</View>) : (<Text style={styles.summaryText}>-</Text>)}');
L.push('          </View>');
L.push('          <View style={styles.spacer} />');
L.push('          <View style={styles.buttonRow}>');
L.push('            <TouchableOpacity style={styles.backButton} onPress={() => router.replace("/register/step6-1" as any)}><Text style={styles.backText}>ย้อนกลับ</Text></TouchableOpacity>');
L.push('            <TouchableOpacity style={styles.nextButton} onPress={handleNext}><Text style={styles.nextText}>ถัดไป</Text></TouchableOpacity>');
L.push('          </View>');
L.push('        </ScrollView>');
L.push('      </SafeAreaView>');
L.push('    </KeyboardAvoidingView>');
L.push('  );');
L.push('}');
L.push('');
fs.writeFileSync(p, L.join("\n"), "utf8");
console.log("step7.tsx written, lines:", L.length);
L.push('                  </View>');
L.push('  }, [form.dislikedFoods]);');
L.push('');
