import { StyleSheet } from 'react-native';

export const ORANGE = '#F26522';
export const BG = '#F0F0F0';

export const FONT_REGULAR = 'NotoSansThai';
export const FONT_BOLD = 'NotoSansThaiBold';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG, position: 'relative' },
  headerBar: { backgroundColor: ORANGE, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 14, paddingHorizontal: 16 },
  backIcon: { padding: 4 },
  headerTitle: { color: '#FFFFFF', fontSize: 20, fontFamily: FONT_BOLD },
  headerRight: { width: 32 },
  content: { padding: 16, flexGrow: 1 },
  sectionTitle: { fontSize: 17, color: '#222222', fontFamily: FONT_BOLD, marginBottom: 12 },
  sectionSubtitle: { fontSize: 13, color: '#999999', fontFamily: FONT_REGULAR, marginBottom: 16, marginTop: -6 },
  categoryCard: { backgroundColor: '#FFFFFF', borderRadius: 14, borderWidth: 1, borderColor: '#E8E8E8', marginBottom: 10, overflow: 'hidden' },
  categoryCardExpanded: { borderColor: '#F26522' },
  categoryHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 14, paddingHorizontal: 16 },
  categoryHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  categoryEmoji: { fontSize: 22 },
  categoryName: { fontSize: 15, fontFamily: FONT_BOLD, color: '#222222' },
  categoryBadge: { backgroundColor: '#FFF3EB', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2, marginLeft: 6 },
  categoryBadgeText: { fontSize: 11, fontFamily: FONT_BOLD, color: '#F26522' },
  subCategoryArea: { backgroundColor: '#FFF3EB', paddingTop: 4, paddingBottom: 8, paddingHorizontal: 12 },
  subCategoryHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, paddingHorizontal: 4 },
  subCategoryName: { fontSize: 14, fontFamily: FONT_BOLD, color: '#D4550E' },
  chipContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 4, paddingBottom: 4 },
  chip: { paddingVertical: 8, paddingHorizontal: 14, borderRadius: 20, borderWidth: 1.5 },
  chipSelected: { backgroundColor: '#F26522', borderColor: '#F26522' },
  chipUnselected: { backgroundColor: '#FFFFFF', borderColor: '#E0E0E0' },
  chipText: { fontSize: 14, fontFamily: FONT_REGULAR },
  chipTextSelected: { color: '#FFFFFF', fontFamily: FONT_BOLD },
  chipTextUnselected: { color: '#666666' },
  selectedStrip: { backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E8E8E8', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8 },
  selectedStripTitle: { fontSize: 13, color: '#D4550E', fontFamily: FONT_BOLD, marginBottom: 8 },
  selectedChip: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#FFF3EB', borderRadius: 16, paddingHorizontal: 10, paddingVertical: 5, borderWidth: 1, borderColor: '#F26522' },
  selectedChipText: { fontSize: 12, color: '#D4550E', fontFamily: FONT_BOLD },
  bottomBar: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, paddingVertical: 12, backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E8E8E8' },
  cancelBtn: { flex: 1, paddingVertical: 14, borderRadius: 12, borderWidth: 1.5, borderColor: '#E0E0E0', backgroundColor: '#F0F0F0', alignItems: 'center', justifyContent: 'center' },
  cancelBtnText: { fontSize: 15, color: '#999999', fontFamily: FONT_BOLD },
  confirmBtn: { flex: 1.5, paddingVertical: 14, borderRadius: 12, backgroundColor: ORANGE, alignItems: 'center', justifyContent: 'center', shadowColor: ORANGE, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 6, elevation: 4 },
  confirmBtnText: { fontSize: 15, color: '#FFFFFF', fontFamily: FONT_BOLD },
  addBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 12, borderWidth: 1.5, borderColor: '#F26522', backgroundColor: '#FFFFFF', marginTop: 12 },
  addBtnText: { fontSize: 15, color: '#F26522', fontFamily: FONT_BOLD },
  saveButton: { backgroundColor: ORANGE, paddingVertical: 16, borderRadius: 14, alignItems: 'center', marginTop: 20, marginBottom: 12, shadowColor: ORANGE, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 6, elevation: 4 },
  saveButtonText: { color: '#FFFFFF', fontSize: 18, fontFamily: FONT_BOLD },
  toast: { position: 'absolute', top: 70, alignSelf: 'center', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, zIndex: 999, shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4, elevation: 5 },
  toastSuccess: { backgroundColor: '#22A06B' },
  toastError: { backgroundColor: '#E53935' },
  toastText: { color: '#FFFFFF', fontSize: 14, fontFamily: FONT_BOLD },
  emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
  emptyText: { fontSize: 15, color: '#999999', fontFamily: FONT_REGULAR, marginTop: 12, textAlign: 'center' },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: '#E8E8E8', paddingHorizontal: 12, marginBottom: 12 },
  searchInput: { flex: 1, paddingVertical: 10, fontSize: 14, color: '#222222', fontFamily: FONT_REGULAR },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  noneText: { fontSize: 13, color: '#999999', fontFamily: FONT_REGULAR, paddingVertical: 4 },
});
